### ISSUE TITLE
Write unit / integration tests for parsing

### ISSUE THREAD

**Issue by zanesterling** [zanesterling/fatr#8]
Make some tests to check that our parsing works on new blank FSes made with mkfs.fat.

**Comment by kallisti5** [comment]
If you want to do travis.ci, something like this might be a good start:
```yaml
language: rust
before_script:
  - mkdir tmp
  - dd if=/dev/zero of=tmp/fat12.img bs=$((1024*1024)) count=8
  - mkfs.fat -F12 -n TEST12 tmp/fat12.img
  - dd if=/dev/zero of=tmp/fat16.img bs=$((1024*1024)) count=32
  - mkfs.fat -F16 -n TEST16 tmp/fat16.img
  - dd if=/dev/zero of=tmp/fat32.img bs=$((1024*1024)) count=32
  - mkfs.fat -F32 -n TEST32 tmp/fat32.img
```

Packing several 32MiB and 8 MiB files in the git repo isn't great.
